import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  CreateDateColumn,
  UpdateDateColumn,
  Index,
  BeforeInsert,
} from 'typeorm';
import { v4 as uuidv4 } from 'uuid';

export enum AmlAlertStatus {
  OPEN = 'OPEN',
  UNDER_REVIEW = 'UNDER_REVIEW',
  ESCALATED = 'ESCALATED',
  CLOSED_NO_ACTION = 'CLOSED_NO_ACTION',
  CLOSED_SAR_FILED = 'CLOSED_SAR_FILED',
  CLOSED_FALSE_POSITIVE = 'CLOSED_FALSE_POSITIVE',
}

export enum AmlAlertSeverity {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum AmlRuleCode {
  // Structuring / smurfing
  STRUCTURING_CASH = 'STRUCTURING_CASH',
  STRUCTURING_TRANSFERS = 'STRUCTURING_TRANSFERS',
  // Velocity
  HIGH_VELOCITY_TRANSFERS = 'HIGH_VELOCITY_TRANSFERS',
  RAPID_MOVEMENT = 'RAPID_MOVEMENT',
  // Amount thresholds
  LARGE_CASH_DEPOSIT = 'LARGE_CASH_DEPOSIT',
  LARGE_WIRE_TRANSFER = 'LARGE_WIRE_TRANSFER',
  CTR_THRESHOLD = 'CTR_THRESHOLD',
  // Geographic
  HIGH_RISK_JURISDICTION = 'HIGH_RISK_JURISDICTION',
  SANCTIONS_COUNTRY = 'SANCTIONS_COUNTRY',
  // Behavioral
  UNUSUAL_ACTIVITY = 'UNUSUAL_ACTIVITY',
  DORMANT_ACCOUNT_ACTIVITY = 'DORMANT_ACCOUNT_ACTIVITY',
  ROUND_DOLLAR_TRANSACTIONS = 'ROUND_DOLLAR_TRANSACTIONS',
}

/**
 * AML alert generated by the transaction monitoring rules engine.
 */
@Entity('aml_alerts')
export class AmlAlert {
  @PrimaryGeneratedColumn('uuid')
  id!: string;

  @Index('idx_aml_alerts_number', { unique: true })
  @Column({ name: 'alert_number', type: 'varchar', length: 25, unique: true })
  alertNumber!: string;

  @Index('idx_aml_alerts_customer_id')
  @Column({ name: 'customer_id', type: 'uuid' })
  customerId!: string;

  @Column({ name: 'account_id', type: 'uuid', nullable: true })
  accountId!: string | null;

  @Column({ name: 'transaction_id', type: 'uuid', nullable: true })
  transactionId!: string | null;

  @Column({ type: 'enum', enum: AmlRuleCode })
  ruleCode!: AmlRuleCode;

  @Column({ type: 'enum', enum: AmlAlertSeverity })
  severity!: AmlAlertSeverity;

  @Column({ type: 'enum', enum: AmlAlertStatus, default: AmlAlertStatus.OPEN })
  status!: AmlAlertStatus;

  @Column({ type: 'text' })
  description!: string;

  /** Data snapshot that triggered the rule */
  @Column({ name: 'trigger_data', type: 'jsonb' })
  triggerData!: Record<string, unknown>;

  /** Risk score 0-100 */
  @Column({ name: 'risk_score', type: 'int', default: 0 })
  riskScore!: number;

  @Column({ name: 'assigned_to_user_id', type: 'uuid', nullable: true })
  assignedToUserId!: string | null;

  @Column({ name: 'assigned_at', type: 'timestamptz', nullable: true })
  assignedAt!: Date | null;

  @Column({ name: 'reviewed_by_user_id', type: 'uuid', nullable: true })
  reviewedByUserId!: string | null;

  @Column({ name: 'reviewed_at', type: 'timestamptz', nullable: true })
  reviewedAt!: Date | null;

  @Column({ name: 'reviewer_notes', type: 'text', nullable: true })
  reviewerNotes!: string | null;

  @Column({ name: 'case_id', type: 'uuid', nullable: true })
  caseId!: string | null;

  @Column({ name: 'due_date', type: 'timestamptz', nullable: true })
  dueDate!: Date | null;

  @CreateDateColumn({ name: 'created_at', type: 'timestamptz' })
  createdAt!: Date;

  @UpdateDateColumn({ name: 'updated_at', type: 'timestamptz' })
  updatedAt!: Date;

  @BeforeInsert()
  generateAlertNumber(): void {
    if (!this.alertNumber) {
      const ts = Date.now().toString().slice(-8);
      const rand = Math.floor(Math.random() * 10000).toString().padStart(4, '0');
      this.alertNumber = `AML-${ts}${rand}`;
    }
  }
}
